{
 "title": "Api overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests served last 5 min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(requests_total[5m])-60"
    }
   ]
  },
  {
   "title": "Request per min last 5 min",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "reqps",
   "targets": [
    {
     "expr": "rate(requests_total[5m]) * 60 -12"
    }
   ]
  },
  {
   "title": "Logins the last 5 min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "logins_total" }
   ]
  },
  {
   "title": "Go Threads",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "avg(go_threads)" }
   ]
  }
 ]
}